# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openworklabs/lotus:v0.4.1
  pullPolicy: IfNotPresent #Always 

ingress:
  enabled: false

ingressApi:
  enabled: false
  host: node.glif.io
  
init:
  sync:
    enabled: true
    # ideally a shared volume containing chain dump
    volume: {}

secretVolume:
  enabled: false

resources:
  requests:
    cpu: 1000m
    memory: 4Gi
  limits:
    cpu: 3000m
    memory: 12Gi

persistence:
  enabled: true
  ## Filecoin data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  lotus:
    size: "500Gi"
    storageClassName: gp2
    accessModes:
      - ReadWriteOnce
