apiVersion: v1
kind: Service
metadata:
  name: lotus-node-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lotus-node-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
